name: 🔒 Branch Protection Setup

on:
  workflow_dispatch:
    inputs:
      force_setup:
        description: 'Force setup even if already configured'
        required: false
        default: 'false'

jobs:
  setup-branch-protection:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Branch Protection
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            
            try {
              // Get current branch protection
              const currentProtection = await github.rest.repos.getBranchProtection({
                owner,
                repo,
                branch: 'main'
              });
              
              console.log('Branch protection already exists:', currentProtection.data);
              
              if (context.payload.inputs.force_setup !== 'true') {
                console.log('Branch protection already configured. Use force_setup=true to override.');
                return;
              }
            } catch (error) {
              if (error.status !== 404) {
                throw error;
              }
              console.log('No existing branch protection found. Setting up...');
            }
            
            // Configure branch protection
            const protection = {
              owner,
              repo,
              branch: 'main',
              required_status_checks: {
                strict: true,
                contexts: [
                  'build-and-test',
                  'content-validation',
                  'security-scan'
                ]
              },
              enforce_admins: false,
              required_pull_request_reviews: {
                required_approving_review_count: 1,
                dismiss_stale_reviews: true,
                require_code_owner_reviews: false,
                require_last_push_approval: false
              },
              restrictions: null,
              allow_force_pushes: false,
              allow_deletions: false,
              block_creations: false,
              required_conversation_resolution: true,
              lock_branch: false,
              allow_fork_syncing: true
            };
            
            try {
              const result = await github.rest.repos.updateBranchProtection(protection);
              console.log('Branch protection configured successfully:', result.data);
              
              // Also set up auto-merge for dependabot PRs
              await github.rest.repos.createOrUpdateEnvironment({
                owner,
                repo,
                environment_name: 'production',
                wait_timer: 0,
                reviewers: [],
                deployment_branch_policy: {
                  protected_branches: true,
                  custom_branch_policies: false
                }
              });
              
              console.log('✅ Branch protection setup complete!');
              console.log('📋 Configuration:');
              console.log('  - Require PR reviews: 1 approving review');
              console.log('  - Require status checks: build-and-test, content-validation, security-scan');
              console.log('  - Dismiss stale reviews: enabled');
              console.log('  - Require conversation resolution: enabled');
              console.log('  - Prevent force pushes: enabled');
              console.log('  - Prevent deletions: enabled');
              
            } catch (error) {
              console.error('Failed to setup branch protection:', error);
              throw error;
            }

